//! Per-pane [`AgentState`] and JSON persistence to `~/.linear-taco/state.json`.
//!
//! The state map survives app restarts so panes can be respawned via
//! `claude --resume <sessionId>` and the dashboard can re-derive phase
//! by re-tailing each session's transcript.

use std::{
    collections::HashMap,
    path::{Path, PathBuf},
    time::{Duration, SystemTime, UNIX_EPOCH},
};

use claude_viewer::events::{SessionId, TodoItem};
use serde::{Deserialize, Serialize};

use crate::phase::AgentPhase;

/// Stable identifier for a terminal pane. Generated by the integration
/// layer and threaded through every IPC channel that writes to the PTY.
/// We use `String` over `Uuid` to keep the wire format trivially
/// loggable and let the host pick its own scheme.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PaneId(pub String);

impl PaneId {
    pub fn new(s: impl Into<String>) -> Self {
        Self(s.into())
    }

    pub fn fresh() -> Self {
        Self(uuid::Uuid::new_v4().to_string())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Cost {
    pub input_tokens: u64,
    pub output_tokens: u64,
    pub usd: f64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct FileChange {
    pub path: PathBuf,
    pub kind: FileChangeKind,
    pub at_unix_ms: u64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FileChangeKind {
    Read,
    Edit,
    Write,
    Created,
    Deleted,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentState {
    pub pane_id: PaneId,
    pub session_id: Option<SessionId>,
    pub cwd: PathBuf,
    pub title: String,
    #[serde(default)]
    pub phase: AgentPhase,
    pub started_at_unix_ms: u64,
    pub last_activity_unix_ms: u64,
    #[serde(default)]
    pub pending_todos: Vec<TodoItem>,
    #[serde(default)]
    pub file_changes: Vec<FileChange>,
    #[serde(default)]
    pub cost: Option<Cost>,
    #[serde(default)]
    pub watch: bool,
    #[serde(default)]
    pub pinned: bool,
    #[serde(default)]
    pub parent_pane_id: Option<PaneId>,
    /// `agent` for `claude` panes, `shell` for plain `$SHELL` panes.
    /// Persisted so reattach knows what to relaunch.
    #[serde(default = "default_kind")]
    pub kind: PaneKind,
}

fn default_kind() -> PaneKind {
    PaneKind::Agent
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PaneKind {
    Agent,
    Shell,
}

impl AgentState {
    pub fn new(pane_id: PaneId, cwd: PathBuf, title: impl Into<String>) -> Self {
        let now = unix_ms_now();
        Self {
            pane_id,
            session_id: None,
            cwd,
            title: title.into(),
            phase: AgentPhase::Idle,
            started_at_unix_ms: now,
            last_activity_unix_ms: now,
            pending_todos: Vec::new(),
            file_changes: Vec::new(),
            cost: None,
            watch: false,
            pinned: false,
            parent_pane_id: None,
            kind: PaneKind::Agent,
        }
    }

    pub fn touch(&mut self) {
        self.last_activity_unix_ms = unix_ms_now();
    }

    pub fn idle_for(&self) -> Duration {
        let now = unix_ms_now();
        Duration::from_millis(now.saturating_sub(self.last_activity_unix_ms))
    }
}

/// JSON-on-disk store for [`AgentState`] keyed by [`PaneId`].
///
/// Writes are debounced by the caller: after mutating, call
/// [`AgentStateStore::save_async`] (or sync [`AgentStateStore::save`]).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AgentStateStore {
    #[serde(default)]
    states: HashMap<String, AgentState>,
}

impl AgentStateStore {
    pub fn new() -> Self {
        Self::default()
    }

    /// Default location: `$HOME/.linear-taco/state.json`. Falls back to
    /// the current working directory if `HOME` is unset.
    pub fn default_path() -> PathBuf {
        let home = std::env::var_os("HOME")
            .map(PathBuf::from)
            .unwrap_or_else(|| std::env::current_dir().unwrap_or_else(|_| PathBuf::from(".")));
        home.join(".linear-taco").join("state.json")
    }

    pub fn load_or_default(path: &Path) -> Self {
        match std::fs::read_to_string(path) {
            Ok(text) if text.trim().is_empty() => Self::new(),
            Ok(text) => serde_json::from_str(&text).unwrap_or_else(|err| {
                tracing::warn!(?err, "linear-taco state.json is malformed; starting fresh");
                Self::new()
            }),
            Err(err) if err.kind() == std::io::ErrorKind::NotFound => Self::new(),
            Err(err) => {
                tracing::warn!(?err, "couldn't read linear-taco state.json; starting fresh");
                Self::new()
            }
        }
    }

    pub fn save(&self, path: &Path) -> std::io::Result<()> {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let pretty = serde_json::to_string_pretty(self).map_err(io_err)?;
        let tmp = path.with_extension("json.tmp");
        std::fs::write(&tmp, pretty)?;
        std::fs::rename(&tmp, path)?;
        Ok(())
    }

    pub fn upsert(&mut self, state: AgentState) {
        self.states.insert(state.pane_id.0.clone(), state);
    }

    pub fn remove(&mut self, pane_id: &PaneId) -> Option<AgentState> {
        self.states.remove(pane_id.as_str())
    }

    pub fn get(&self, pane_id: &PaneId) -> Option<&AgentState> {
        self.states.get(pane_id.as_str())
    }

    pub fn get_mut(&mut self, pane_id: &PaneId) -> Option<&mut AgentState> {
        self.states.get_mut(pane_id.as_str())
    }

    pub fn iter(&self) -> impl Iterator<Item = &AgentState> {
        self.states.values()
    }

    pub fn iter_mut(&mut self) -> impl Iterator<Item = &mut AgentState> {
        self.states.values_mut()
    }

    pub fn len(&self) -> usize {
        self.states.len()
    }

    pub fn is_empty(&self) -> bool {
        self.states.is_empty()
    }
}

fn unix_ms_now() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}

fn io_err(e: serde_json::Error) -> std::io::Error {
    std::io::Error::other(e)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn upsert_replaces_state_for_same_pane() {
        let mut store = AgentStateStore::new();
        let pid = PaneId::new("p1");
        let mut s = AgentState::new(pid.clone(), PathBuf::from("/tmp"), "first");
        store.upsert(s.clone());
        s.title = "second".into();
        store.upsert(s);
        assert_eq!(store.len(), 1);
        assert_eq!(store.get(&pid).unwrap().title, "second");
    }

    #[test]
    fn save_then_load_roundtrips() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("state.json");
        let mut store = AgentStateStore::new();
        let mut state = AgentState::new(PaneId::new("p1"), PathBuf::from("/foo"), "title");
        state.session_id = Some("sess".into());
        state.watch = true;
        state.pinned = true;
        state.file_changes.push(FileChange {
            path: PathBuf::from("/foo/bar.rs"),
            kind: FileChangeKind::Edit,
            at_unix_ms: 1,
        });
        store.upsert(state);
        store.save(&path).unwrap();

        let reloaded = AgentStateStore::load_or_default(&path);
        assert_eq!(reloaded.len(), 1);
        let s = reloaded.get(&PaneId::new("p1")).unwrap();
        assert!(s.watch);
        assert!(s.pinned);
        assert_eq!(s.session_id.as_deref(), Some("sess"));
        assert_eq!(s.file_changes.len(), 1);
    }

    #[test]
    fn malformed_state_file_falls_back_to_empty() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("state.json");
        std::fs::write(&path, "not json").unwrap();
        let store = AgentStateStore::load_or_default(&path);
        assert!(store.is_empty());
    }
}
